#!/bin/bash
cd $(cd $(dirname $0); pwd)
echo -e '\e[1m\e[31m
Storm source is being installed, 
Please wait until the installation is complete
\033[0m'
echo -e '\033[0;33m
If it is the first time to install the source, send the number » {1}
or اذا كانت اول مره تنصيب السورس ارسل رقم » {1}
If you have already installed the source, send the number » {2}
or اذا سبق ونصبت السورس ارسل رقم » {2}
\033[0m'
read Install
case $Install in
1)
echo -e '\033[0;33mOffice installation has begun'
sleep 2
apt update
apt upgrade
apt-get update
apt-get upgrade
apt install lua5.2
 wget https://luarocks.org/releases/luarocks-2.4.3.tar.gz
 tar zxpf luarocks-2.4.3.tar.gz
cd luarocks-2.4.3
./configure; make bootstrap
luarocks install luasocket
luarocks install luasec
luarocks install luautf8
luarocks install redis-lua
 luarocks remove lua-cjson2
 luarocks remove lua-cjson
 apt-get install lua-cjson
luarocks install Lua-cURL
cd ..
apt-get install tmux
apt-get install luarocks
apt-get install screen
apt install zip
apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev lua-socket lua-sec lua-expat libevent-dev make unzip git redis-server autoconf g++ libjansson-dev libpython-dev expat libexpat1-dev
apt-get update
apt-get install
apt-get install upstart-sysv
wget http://luarocks.org/releases/luarocks-2.2.2.tar.gz;tar zxpf luarocks-2.2.2.tar.gz;cd luarocks-2.2.2 && ./configure
make bootstrap
luarocks install luasocket
luarocks install luasec
luarocks install lua-term
luarocks install Lua-cURL
service redis-server start
apt-get install libconfig++9v5 -y 
apt-get install libstdc++6 -y
add-apt-repository ppa:ubuntu-toolchain-r/test -y 
apt-get install lua-lgi -y  
apt-get install software-properties-common -y
apt-get install libnotify-dev -y 
apt-get install lua-space -y
apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev lua-socket lua-sec lua-expat libevent-dev make unzip git redis-server autoconf g++ libjansson-dev libpython-dev expat libexpat1-dev -y
apt install python3.8
apt install python3-pip
python3.8 -m pip install -U pip
python3.8 -m pip install -U setuptools
python3.8 -m pip install yt-dlp -U
python3.8 -m pip install ffmpeg 
apt install ffmpeg 
apt install gnome-calculator
python3.8 -m pip install gtts -U
python3.8 -m pip install -U nsfw-detector
python3.8 -m pip install -U opencv-python
apt-get update 
apt-get upgrade -y
cd ..
rm -rf luarocks*
unzip tdlua.zip
mv tdlua.so /usr/lib/x86_64-linux-gnu/lua/5.2/tdlua.so
rm -fr tdlua.zip
lua5.2 Fast.lua
;;
2)
echo -e "\e[1m\e[32mThe bot is running now : جاري تشغيل البوت الان : \e[0m"
sleep 2
unzip tdlua.zip
mv tdlua.so /usr/lib/x86_64-linux-gnu/lua/5.2/tdlua.so
rm -fr tdlua.zip
lua5.2 Fast.lua
;;
esac